language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
   - mysql
install:
    - pip install -r backend/requirements.txt
before_script:
    - touch backend/stoare/stoare/local_settings.py
    - mysql -e 'create database test;' -u root
script:
    -  python backend/stoare/manage.py test shop product user_auth
