language: python
python:
- '3.7'
env:
- SECRET_KEY='TEST'
services:
- mysql
install:
- pip install -r backend/requirements.txt
before_script:
- touch backend/stoare/stoare/local_settings.py
- mysql -e 'create database test;' -u root
script:
- python backend/stoare/manage.py test shop product user_auth
after_success:
- bash ./deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
- cd client