language: python

python:
    - "3.6"
env:
    - SECRET_KEY='TEST'
services:
   - mysql
install:
    - pip install -r backend/requirements.txt
before_script:
    - mysql -e 'create database test;' -u root
script:
    -  python backend/stoare/manage.py test
